import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { getCredential } from './credentials.js';

export type SlotName = 'opus' | 'sonnet' | 'haiku';
/** A slot maps to a real model name, or delegates to another profile (SPEC-PROVIDERS §3). */
export type SlotTarget = string | { profile: string };

/** Discriminated union (DESIGN-OAUTH §3.1): credential SOURCE, orthogonal to the protocol axis (ADR-17). */
export type AuthConfig =
  | {
      type: 'bearer' | 'x-api-key';
      /** Env var name holding the key. Keys never live in the config file. */
      apiKeyRef: string;
    }
  | {
      type: 'oauth';
      /** Credential-store key; defaults to the profile's provider. */
      provider?: string;
    }
  | {
      /** Local providers (SPEC-PROVIDERS §3ter): no credential, constant Bearer sent. */
      type: 'none';
    };

export type ApiKeyAuth = Extract<AuthConfig, { apiKeyRef: string }>;

export interface ProfileConfig {
  provider: string;
  /**
   * 'responses' is the M6a lane: the OpenAI Responses API over WHAM.
   * 'codeassist' is the M6b lane: Google Code Assist. Both serve an OAuth
   * subscription whose token does not spend on the provider's public API.
   */
  mode: 'passthrough' | 'translate' | 'responses' | 'codeassist';
  baseUrl?: string;
  auth: AuthConfig;
  slots: Record<SlotName, SlotTarget>;
  quirks?: string[];
  limits?: { maxOutputTokens?: number };
  /** Opt-in: profile to retry through ONCE on 429/5xx/network (SPEC-PROVIDERS §4ter). */
  failover?: string;
  /** Opt-in content-aware routing (SPEC-PROVIDERS §4quater). */
  routes?: RoutesConfig;
  /** Model → context window in token: dynamic longContext threshold (§4quater). */
  contextWindows?: Record<string, number>;
  /** Ultimo esito di `lupin doctor` (SPEC-CLI §3), metadata sola. */
  lastDoctor?: { score: number; max: number; date: string };
}

export interface RoutesConfig {
  /** threshold absent = dynamic: 0.8 × window of the pre-routing resolved model (§4quater). */
  longContext?: { threshold?: number; target: SlotTarget };
  vision?: { target: SlotTarget };
  thinking?: { target: SlotTarget };
}

export interface LupinConfig {
  activeProfile: string;
  port: number;
  localToken: string;
  profiles: Record<string, ProfileConfig>;
  /**
   * Agent routes (SPEC-PROVIDERS §4decies, ADR-47): the id
   * `claude-lupin-agent:<name>` resolves through this table. Global, not per
   * profile: the routing describes the harness, not a provider. A string
   * target is a model of the profile serving the request; a delegation lands
   * on the target profile's sonnet slot (an agent id names no tier).
   */
  agents?: Record<string, SlotTarget>;
}

/**
 * Same charset as the §4nonies account labels: a `:` would make the published
 * id ambiguous, a space would break the frontmatter value that carries it.
 */
export const AGENT_NAME_RE = /^[A-Za-z0-9._-]{1,32}$/;

export function defaultConfigPath(): string {
  // LUPIN_DIR must move the WHOLE home, config included: honoring it only for
  // pidfile/log while the config still came from ~/.lupin gave a split-brain
  // daemon (found live by the 2026-07-24 npm-pack smoke: scratch home, real
  // user config). LUPIN_CONFIG stays as the file-level override.
  const dir = process.env.LUPIN_DIR ?? join(homedir(), '.lupin');
  return process.env.LUPIN_CONFIG ?? join(dir, 'config.json');
}

export function loadConfig(path: string = defaultConfigPath()): LupinConfig {
  const raw = readFileSync(path, 'utf8');
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    throw new Error(`config ${path} is not valid JSON: ${e instanceof Error ? e.message : String(e)}`);
  }
  return validateConfig(parsed);
}

const SLOT_NAMES: SlotName[] = ['opus', 'sonnet', 'haiku'];

export function validateConfig(value: unknown): LupinConfig {
  if (value === null || typeof value !== 'object') throw new Error('config: expected a JSON object');
  const c = value as Record<string, unknown>;
  if (typeof c['activeProfile'] !== 'string' || c['activeProfile'] === '') {
    throw new Error('config: "activeProfile" must be a non-empty string');
  }
  if (typeof c['port'] !== 'number' || !Number.isInteger(c['port'])) {
    throw new Error('config: "port" must be an integer');
  }
  if (typeof c['localToken'] !== 'string' || c['localToken'] === '') {
    throw new Error('config: "localToken" must be a non-empty string (generated by lupin init)');
  }
  if (c['profiles'] === null || typeof c['profiles'] !== 'object') {
    throw new Error('config: "profiles" must be an object');
  }
  const profiles = c['profiles'] as Record<string, unknown>;
  for (const [name, p] of Object.entries(profiles)) {
    validateProfile(name, p);
    const failover = (p as Record<string, unknown>)['failover'];
    if (failover !== undefined) {
      if (typeof failover !== 'string' || failover === '') {
        throw new Error(`config: profile "${name}": "failover" must be a non-empty profile name`);
      }
      if (!(failover in profiles)) {
        throw new Error(`config: profile "${name}": failover profile "${failover}" is not defined`);
      }
    }
    const rec = p as Record<string, unknown>;
    const windows = rec['contextWindows'] as Record<string, unknown> | undefined;
    validateRoutes(name, rec['routes'], profiles, windows !== undefined && Object.keys(windows).length > 0);
  }
  if (!(c['activeProfile'] in profiles)) {
    throw new Error(`config: activeProfile "${c['activeProfile']}" is not defined in profiles`);
  }
  validateAgents(c['agents'], profiles);
  return value as LupinConfig;
}

/** Agent routes (§4decies): names on the sentinel charset, slot-shaped targets. */
function validateAgents(value: unknown, profiles: Record<string, unknown>): void {
  if (value === undefined) return;
  const where = 'config: "agents"';
  if (value === null || typeof value !== 'object') throw new Error(`${where} must be an object`);
  for (const [name, target] of Object.entries(value as Record<string, unknown>)) {
    if (!AGENT_NAME_RE.test(name)) {
      throw new Error(`${where}: "${name}" is not a valid agent name (allowed: A-Z a-z 0-9 . _ -, max 32)`);
    }
    const isModel = typeof target === 'string' && target !== '';
    const isDelegation =
      target !== null && typeof target === 'object' && typeof (target as Record<string, unknown>)['profile'] === 'string';
    if (!isModel && !isDelegation) {
      throw new Error(`${where}.${name}: target must be a model name or {"profile": "<name>"}`);
    }
    if (isDelegation) {
      const ref = (target as Record<string, unknown>)['profile'] as string;
      if (!(ref in profiles)) throw new Error(`${where}.${name}: target profile "${ref}" is not defined`);
    }
  }
}

const ROUTE_KEYS = ['longContext', 'vision', 'thinking'] as const;

function validateRoutes(name: string, value: unknown, profiles: Record<string, unknown>, hasWindows: boolean): void {
  if (value === undefined) return;
  const where = `config: profile "${name}": "routes"`;
  if (value === null || typeof value !== 'object') throw new Error(`${where} must be an object`);
  const routes = value as Record<string, unknown>;
  for (const key of Object.keys(routes)) {
    if (!(ROUTE_KEYS as readonly string[]).includes(key)) {
      throw new Error(`${where}: unknown route "${key}" (valid: ${ROUTE_KEYS.join(', ')})`);
    }
    const route = routes[key] as Record<string, unknown> | null;
    if (route === null || typeof route !== 'object') throw new Error(`${where}.${key} must be an object`);
    if (key === 'longContext') {
      const threshold = route['threshold'];
      if (threshold !== undefined && (typeof threshold !== 'number' || threshold <= 0)) {
        throw new Error(`${where}.longContext: "threshold" must be a positive number`);
      }
      if (threshold === undefined && !hasWindows) {
        throw new Error(
          `${where}.longContext: without "threshold" the profile needs "contextWindows" (dynamic threshold, §4quater)`,
        );
      }
    }
    const target = route['target'];
    const targetOk =
      (typeof target === 'string' && target !== '') ||
      (target !== null &&
        typeof target === 'object' &&
        typeof (target as Record<string, unknown>)['profile'] === 'string');
    if (!targetOk) throw new Error(`${where}.${key}: "target" must be a model name or {"profile": "<name>"}`);
    if (typeof target === 'object' && target !== null) {
      const ref = (target as Record<string, unknown>)['profile'] as string;
      if (!(ref in profiles)) throw new Error(`${where}.${key}: target profile "${ref}" is not defined`);
    }
  }
}

function validateProfile(name: string, value: unknown): void {
  const where = `config: profile "${name}"`;
  if (value === null || typeof value !== 'object') throw new Error(`${where} must be an object`);
  const p = value as Record<string, unknown>;
  if (typeof p['provider'] !== 'string') throw new Error(`${where}: "provider" must be a string`);
  if (
    p['mode'] !== 'passthrough' &&
    p['mode'] !== 'translate' &&
    p['mode'] !== 'responses' &&
    p['mode'] !== 'codeassist'
  ) {
    throw new Error(`${where}: "mode" must be "passthrough", "translate" or "responses"`);
  }
  const auth = p['auth'] as Record<string, unknown> | null | undefined;
  if (auth == null || typeof auth !== 'object') {
    throw new Error(`${where}: "auth" must be an object`);
  }
  if (auth['type'] === 'oauth') {
    if (auth['provider'] !== undefined && (typeof auth['provider'] !== 'string' || auth['provider'] === '')) {
      throw new Error(`${where}: "auth.provider" must be a non-empty string when present`);
    }
  } else if (auth['type'] === 'bearer' || auth['type'] === 'x-api-key') {
    if (typeof auth['apiKeyRef'] !== 'string' || auth['apiKeyRef'] === '') {
      throw new Error(`${where}: "auth.apiKeyRef" must name an env var (keys never live in the config)`);
    }
  } else if (auth['type'] !== 'none') {
    throw new Error(`${where}: "auth.type" must be "bearer", "x-api-key", "oauth" or "none"`);
  }
  const windows = p['contextWindows'];
  if (windows !== undefined) {
    if (windows === null || typeof windows !== 'object') throw new Error(`${where}: "contextWindows" must be an object`);
    for (const [model, w] of Object.entries(windows as Record<string, unknown>)) {
      if (typeof w !== 'number' || !Number.isFinite(w) || w <= 0) {
        throw new Error(`${where}: "contextWindows.${model}" must be a positive number of tokens`);
      }
    }
  }
  const slots = p['slots'] as Record<string, unknown> | null | undefined;
  if (slots == null || typeof slots !== 'object') throw new Error(`${where}: "slots" must be an object`);
  for (const slot of SLOT_NAMES) {
    const t = slots[slot];
    const isModel = typeof t === 'string' && t !== '';
    const isDelegation =
      t !== null && typeof t === 'object' && typeof (t as Record<string, unknown>)['profile'] === 'string';
    if (!isModel && !isDelegation) {
      throw new Error(`${where}: slot "${slot}" must be a model name or {"profile": "<name>"}`);
    }
  }
}

/** Env var wins; the credential store (~/.lupin/credentials.json, 600) is the fallback. */
export function resolveApiKey(auth: ApiKeyAuth): string | undefined {
  return process.env[auth.apiKeyRef] ?? getCredential(auth.apiKeyRef);
}

/** Atomic save (tmp+rename), validating first so a broken config never lands on disk. */
export function saveConfig(config: LupinConfig, path: string = defaultConfigPath()): void {
  validateConfig(config);
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(config, null, 2)}\n`);
  renameSync(tmp, path);
}
