// `lupin doctor --submit` (SPEC-CLI §3.3): turns a finished doctor run into a
// PRE-FILLED GitHub issue, and nothing else. No backend, no telemetry, no
// silent upload: the command builds a URL, prints it, and the user decides
// whether to open it and press submit (SPEC-CLI §4.3: the scoreboard receives
// explicit submissions only).
//
// What travels: provider, mode, model, score, the per-check breakdown and the
// measured metrics. What never travels: credentials, prompts, responses, log
// bodies, and the profile's baseUrl: a local or private endpoint is the
// user's business, not the scoreboard's.

import type { ProfileConfig } from '../config/config.js';
import { CLIENT_URL } from '../providers/identity.js';
import { DOCTOR_THRESHOLD } from './plan.js';
import { cacheReceiptLine, type DoctorRunResult } from './run.js';

export interface SubmissionInput {
  result: DoctorRunResult;
  profile: ProfileConfig;
  profileName: string;
  version: string;
  /** Runtime line, e.g. "win32, node v24.4.0". */
  runtime: string;
  /** YYYY-MM-DD of the run. */
  date: string;
}

/** GitHub rejects very long query strings; the body is trimmed well before that. */
const MAX_BODY = 6000;

export function submissionTitle(input: SubmissionInput): string {
  return `[compat] ${input.profile.provider} / ${input.result.model}`;
}

/** Markdown following .github/ISSUE_TEMPLATE/provider-report.md. */
export function submissionBody(input: SubmissionInput): string {
  const { result, profile } = input;
  const report = result.report;
  const lines: string[] = [];
  lines.push('## Provider and model', '');
  lines.push(`- Provider: \`${profile.provider}\``);
  lines.push(`- Model: \`${result.model}\``);
  lines.push(`- Mode: ${profile.mode}`);
  lines.push(`- Auth: ${profile.auth.type}`);
  lines.push(`- Test date: ${input.date}`);
  lines.push(`- Lupin: v${input.version} (${input.runtime})`);
  if (profile.quirks !== undefined && profile.quirks.length > 0) {
    lines.push(`- Active quirks: ${profile.quirks.join(', ')}`);
  }
  lines.push('');

  if (report === undefined) {
    // Voided run (ADR-23): there is no verdict to report, only its cause.
    lines.push('## Outcome', '', `Doctor did NOT run: ${result.notRun ?? 'cause not recorded'}`, '');
  } else {
    lines.push('## Score', '', `**${String(report.score)}/${String(report.max)}** (threshold ${String(DOCTOR_THRESHOLD)}): ${report.passed ? 'passed' : 'below threshold'}`, '');
    lines.push('| # | Check | Points | Detail |', '|---|---|---|---|');
    for (const ch of report.checks) {
      lines.push(`| ${String(ch.id)} | ${ch.name} | ${String(ch.points)}/${String(ch.max)} | ${oneLine(ch.detail)} |`);
    }
    lines.push('');
  }

  lines.push('## Measurements', '');
  lines.push(`- Duration: ${String(Math.round(result.durationMs / 1000))}s`);
  if (result.metrics !== undefined) {
    const m = result.metrics;
    lines.push(
      `- Requests: ${String(m.requests)}, average latency ${String(m.avgLatencyMs)}ms, tokens in/out ${String(m.inputTokens)}/${String(m.outputTokens)}`,
    );
    const receipt = cacheReceiptLine(m);
    if (receipt !== undefined) lines.push(`- ${oneLine(receipt)}`);
  }
  if (result.cacheControl !== undefined) {
    lines.push(`- cache_control: ${result.cacheControl.outcome}${result.cacheControl.detail === '' ? '' : ` (${oneLine(result.cacheControl.detail)})`}`);
  }
  if (result.dialects.length > 0) {
    lines.push(`- Dialect normalizations that fired: ${result.dialects.join(', ')} (the proxy helped this score)`);
  }
  if (result.sessionError !== undefined) lines.push(`- Session note: ${oneLine(result.sessionError)}`);
  lines.push('');
  lines.push('## What does NOT work', '', '<!-- add here the symptoms the doctor does not cover -->', '');
  lines.push('---', '', `Generated by \`lupin doctor --submit\` (${CLIENT_URL}). No credentials, no prompts, no responses: only the numbers above.`);

  const body = lines.join('\n');
  return body.length <= MAX_BODY ? body : `${body.slice(0, MAX_BODY)}\n\n<!-- truncated -->`;
}

/** Pre-filled issue URL. Never opened by itself: the caller shows it first. */
export function submissionUrl(input: SubmissionInput, repoUrl: string = CLIENT_URL): string {
  const params = new URLSearchParams({
    template: 'provider-report.md',
    labels: 'provider-compat',
    title: submissionTitle(input),
    body: submissionBody(input),
  });
  return `${repoUrl}/issues/new?${params.toString()}`;
}

/** Table cells and bullets break on newlines; details are free text. */
function oneLine(s: string): string {
  return s.replace(/\s*\n+\s*/g, ' ').replace(/\|/g, '\\|').trim();
}
